name: Sync develop with main

# Trigger workflow on push to main
on:
  push:
    branches:
      - main

jobs:
  update-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          # Fetch all branches and the entire commit history
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Checkout develop branch
        run: git checkout develop
        # Ensures the remote develop branch is fully fetched
        continue-on-error: true

      - name: Merge main into develop
        run: git merge origin/main

      - name: Push changes to develop
        run: git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
